import type {
  Brand,
  BrandSettings,
  BrandFonts,
  BlockType,
  BlockVisibility,
  WorksheetSettings,
  InlineChoicesBlock,
  InlineChoiceItem,
} from "./worksheet";

// ─── Migration helpers ──────────────────────────────────────

export function migrateInlineChoicesBlock(block: InlineChoicesBlock): InlineChoiceItem[] {
  if (block.items && block.items.length > 0) {
    return block.items.map((item) => ({
      ...item,
      content: migrateChoiceSyntaxInline(item.content),
    }));
  }
  if (!block.content) return [];
  return block.content
    .split("\n")
    .filter((line) => line.trim().length > 0)
    .map((line, i) => ({
      id: `ic${Date.now()}-${i}`,
      content: migrateChoiceSyntaxInline(line),
    }));
}

function migrateChoiceSyntaxInline(content: string): string {
  return content.replace(/\{\{choice:([^}]+)\}\}/g, (_match, inner: string) => {
    const opts = inner.split("|");
    const starIdx = opts.findIndex((o: string) => o.startsWith("*"));
    if (starIdx >= 0) {
      const correct = opts[starIdx].slice(1);
      const rest = opts.filter((_: string, i: number) => i !== starIdx);
      return `{{${[correct, ...rest].join("|")}}}`;
    }
    return `{{${opts.join("|")}}}`;
  });
}

// ─── Brand defaults ─────────────────────────────────────────

export const DEFAULT_BRAND_SETTINGS: Record<Brand, BrandSettings> = {
  edoomio: {
    logo: "/logo/arbeitsblatt_logo_full_brand.svg",
    organization: "",
    teacher: "",
    headerRight: "",
    footerLeft: "",
    footerCenter: "",
    footerRight: "",
  },
  lingostar: {
    logo: "/logo/lingostar_logo_icon_flat.svg",
    organization: "",
    teacher: "",
    headerRight: "",
    footerLeft: "",
    footerCenter: "",
    footerRight: "",
  },
};

export const BRAND_FONTS: Record<Brand, BrandFonts> = {
  edoomio: {
    bodyFont: "Asap Condensed, sans-serif",
    headlineFont: "Asap Condensed, sans-serif",
    headlineWeight: 700,
    subHeadlineFont: "Asap Condensed, sans-serif",
    subHeadlineWeight: 700,
    headerFooterFont: "Asap Condensed, sans-serif",
    googleFontsUrl:
      "https://fonts.googleapis.com/css2?family=Asap+Condensed:wght@400;600;700&display=swap",
    primaryColor: "#1a1a1a",
  },
  lingostar: {
    bodyFont: "Encode Sans, sans-serif",
    headlineFont: "Merriweather, serif",
    headlineWeight: 400,
    subHeadlineFont: "Encode Sans, sans-serif",
    subHeadlineWeight: 600,
    headerFooterFont: "Encode Sans, sans-serif",
    googleFontsUrl:
      "https://fonts.googleapis.com/css2?family=Encode+Sans:wght@400;500;600&family=Merriweather:wght@400;700&family=Nunito:wght@400;600;700;800&display=swap",
    primaryColor: "#3a4f40",
  },
};

export const BRAND_ICON_LOGOS: Record<Brand, string> = {
  edoomio: "/logo/arbeitsblatt_logo_icon.svg",
  lingostar: "/logo/lingostar_logo_icon_flat.svg",
};

// ─── Default settings ───────────────────────────────────────

export const DEFAULT_SETTINGS: WorksheetSettings = {
  pageSize: "a4",
  orientation: "portrait",
  margins: { top: 20, right: 20, bottom: 20, left: 20 },
  showHeader: true,
  showFooter: true,
  headerText: "",
  footerText: "",
  fontSize: 14,
  fontFamily: "Asap Condensed, sans-serif",
  brand: "edoomio",
  brandSettings: DEFAULT_BRAND_SETTINGS["edoomio"],
  coverSubtitle: "Arbeitsblatt",
  coverInfoText: "",
  coverImages: [],
  coverImageBorder: false,
};

// ─── Block library definitions ──────────────────────────────

export interface BlockDefinition {
  type: BlockType;
  label: string;
  description: string;
  labelKey: string;
  descriptionKey: string;
  icon: string;
  category: "layout" | "content" | "interactive" | "ai-tools";
  translations?: Record<string, { label: string; description: string }>;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  defaultData: Record<string, any> & { type: BlockType; visibility: BlockVisibility };
}

export const BLOCK_LIBRARY: BlockDefinition[] = [
  // ── Content blocks ──
  {
    type: "heading",
    label: "Heading",
    description: "Title or section heading",
    labelKey: "heading",
    descriptionKey: "headingDesc",
    icon: "Heading",
    category: "content",
    translations: { de: { label: "Überschrift", description: "Titel und Überschriften hinzufügen" } },
    defaultData: { type: "heading", content: "Heading", level: 1, visibility: "both" },
  },
  {
    type: "text",
    label: "Text",
    description: "Rich text paragraph",
    labelKey: "text",
    descriptionKey: "textDesc",
    icon: "Type",
    category: "content",
    translations: { de: { label: "Text", description: "Absätze mit formatiertem Text" } },
    defaultData: { type: "text", content: "<p>Enter text here...</p>", visibility: "both" },
  },
  {
    type: "image",
    label: "Image",
    description: "Insert an image",
    labelKey: "image",
    descriptionKey: "imageDesc",
    icon: "Image",
    category: "content",
    translations: { de: { label: "Bild", description: "Bilder und Abbildungen einfügen" } },
    defaultData: { type: "image", src: "", alt: "", visibility: "both" },
  },
  {
    type: "image-cards",
    label: "Image Cards",
    description: "Grid of images with captions",
    labelKey: "imageCards",
    descriptionKey: "imageCardsDesc",
    icon: "LayoutGrid",
    category: "content",
    translations: { de: { label: "Bildkarten", description: "Bilder im Raster mit Beschriftung" } },
    defaultData: {
      type: "image-cards",
      items: [
        { id: "card1", src: "", alt: "", text: "Caption 1" },
        { id: "card2", src: "", alt: "", text: "Caption 2" },
      ],
      columns: 2,
      imageAspectRatio: "1:1",
      imageScale: 100,
      showWritingLines: false,
      writingLinesCount: 1,
      showWordBank: false,
      visibility: "both",
    },
  },
  {
    type: "text-cards",
    label: "Text Cards",
    description: "Grid of text items with optional writing lines",
    labelKey: "textCards",
    descriptionKey: "textCardsDesc",
    icon: "LayoutList",
    category: "content",
    translations: { de: { label: "Textkarten", description: "Text im Raster mit Schreiblinien" } },
    defaultData: {
      type: "text-cards",
      items: [
        { id: "card1", text: "Text 1", caption: "Caption 1" },
        { id: "card2", text: "Text 2", caption: "Caption 2" },
      ],
      columns: 2,
      textSize: "base",
      textAlign: "center",
      textBold: false,
      textItalic: false,
      showBorder: true,
      showWritingLines: false,
      writingLinesCount: 1,
      showWordBank: false,
      visibility: "both",
    },
  },
  {
    type: "glossary",
    label: "Glossary",
    description: "Term-definition list",
    labelKey: "glossary",
    descriptionKey: "glossaryDesc",
    icon: "BookOpen",
    category: "content",
    translations: { de: { label: "Glossar", description: "Begriffe und Definitionen" } },
    defaultData: {
      type: "glossary",
      instruction: "",
      pairs: [
        { id: "g1", term: "Term 1", definition: "Definition 1" },
        { id: "g2", term: "Term 2", definition: "Definition 2" },
        { id: "g3", term: "Term 3", definition: "Definition 3" },
      ],
      visibility: "both",
    },
  },
  {
    type: "chart",
    label: "Chart",
    description: "Bar, pie, or line chart",
    labelKey: "chart",
    descriptionKey: "chartDesc",
    icon: "BarChart3",
    category: "content",
    translations: { de: { label: "Diagramm", description: "Balken-, Kreis- oder Liniendiagramm" } },
    defaultData: {
      type: "chart",
      chartType: "bar",
      title: "",
      data: [
        { id: "d1", label: "A", value: 40, color: "#6366f1" },
        { id: "d2", label: "B", value: 70, color: "#8b5cf6" },
        { id: "d3", label: "C", value: 55, color: "#a78bfa" },
        { id: "d4", label: "D", value: 90, color: "#c4b5fd" },
      ],
      showLegend: false,
      showValues: true,
      showGrid: true,
      xAxisLabel: "",
      yAxisLabel: "",
      visibility: "both",
    },
  },
  {
    type: "numbered-label",
    label: "Numbered Label",
    description: "Auto-incrementing numbered label with optional text",
    labelKey: "numberedLabel",
    descriptionKey: "numberedLabelDesc",
    icon: "Hash",
    category: "content",
    translations: { de: { label: "Nummerierung", description: "Fortlaufende Nummerierung mit optionalem Text" } },
    defaultData: { type: "numbered-label", startNumber: 1, prefix: "", suffix: "", visibility: "both" },
  },
  {
    type: "text-snippet",
    label: "Text Snippet",
    description: "Text block with copy-to-clipboard",
    labelKey: "textSnippet",
    descriptionKey: "textSnippetDesc",
    icon: "ClipboardCopy",
    category: "content",
    translations: { de: { label: "Textbaustein", description: "Textblock mit Kopieren-Funktion" } },
    defaultData: { type: "text-snippet", content: "<p>Enter text here...</p>", visibility: "both" },
  },
  {
    type: "email-skeleton",
    label: "Email",
    description: "Simulated email message",
    labelKey: "emailSkeleton",
    descriptionKey: "emailSkeletonDesc",
    icon: "Mail",
    category: "content",
    translations: { de: { label: "E-Mail", description: "Simulierte E-Mail-Nachricht" } },
    defaultData: {
      type: "email-skeleton",
      from: "anna@example.com",
      to: "ben@example.com",
      subject: "Betreff",
      body: "<p>Hallo Ben,</p><p>…</p><p>Viele Grüße<br/>Anna</p>",
      emailStyle: "none",
      attachments: [],
      visibility: "both",
    },
  },
  {
    type: "job-application",
    label: "Job Application",
    description: "Simulated job application form",
    labelKey: "jobApplication",
    descriptionKey: "jobApplicationDesc",
    icon: "ClipboardList",
    category: "content",
    translations: { de: { label: "Bewerbung", description: "Simuliertes Bewerbungsformular" } },
    defaultData: {
      type: "job-application",
      firstName: "Anna",
      applicantName: "Müller",
      email: "anna@example.com",
      phone: "+49 123 456789",
      position: "Verkäufer/in",
      message: "<p>Sehr geehrte Damen und Herren,</p><p>…</p><p>Mit freundlichen Grüßen<br/>Anna Müller</p>",
      applicationStyle: "none",
      visibility: "both",
    },
  },
  {
    type: "text-comparison",
    label: "Text Comparison",
    description: "Compare two text variants side by side",
    labelKey: "textComparison",
    descriptionKey: "textComparisonDesc",
    icon: "Columns2",
    category: "content",
    translations: { de: { label: "Textvergleich", description: "Zwei Textvarianten nebeneinander vergleichen" } },
    defaultData: { type: "text-comparison", leftContent: "<p></p>", rightContent: "<p></p>", visibility: "both" },
  },
  {
    type: "dos-and-donts",
    label: "Dos & Don'ts",
    description: "List of recommended and discouraged actions",
    labelKey: "dosAndDonts",
    descriptionKey: "dosAndDontsDesc",
    icon: "ListChecks",
    category: "content",
    translations: { de: { label: "Dos & Don'ts", description: "Empfohlene und nicht empfohlene Handlungen" } },
    defaultData: {
      type: "dos-and-donts",
      layout: "horizontal",
      showTitles: true,
      dosTitle: "Do",
      dontsTitle: "Don't",
      dos: [{ id: "do-1", text: "" }],
      donts: [{ id: "dont-1", text: "" }],
      visibility: "both",
    },
  },
  {
    type: "numbered-items",
    label: "Numbered Items",
    description: "Numbered text items with rich content",
    labelKey: "numberedItems",
    descriptionKey: "numberedItemsDesc",
    icon: "ListOrdered",
    category: "content",
    translations: { de: { label: "Nummerierte Punkte", description: "Nummerierte Textabschnitte" } },
    defaultData: {
      type: "numbered-items",
      items: [{ id: "ni-1", content: "" }],
      startNumber: 1,
      bgColor: "",
      borderRadius: 8,
      visibility: "both",
    },
  },
  {
    type: "accordion",
    label: "Accordion",
    description: "Collapsible sections with nested blocks",
    labelKey: "accordion",
    descriptionKey: "accordionDesc",
    icon: "ChevronDown",
    category: "content",
    translations: { de: { label: "Akkordeon", description: "Aufklappbare Abschnitte mit verschachtelten Blöcken" } },
    defaultData: {
      type: "accordion",
      items: [{ id: "acc-1", title: "", children: [] }],
      showNumbers: false,
      visibility: "both",
    },
  },
  {
    type: "table",
    label: "Table",
    description: "Flexible table with rich text cells",
    labelKey: "table",
    descriptionKey: "tableDesc",
    icon: "Table",
    category: "content",
    translations: { de: { label: "Tabelle", description: "Flexible Tabelle mit formatierbaren Zellen" } },
    defaultData: {
      type: "table",
      content:
        '<table><tbody><tr><th colspan="1" rowspan="1"><p></p></th><th colspan="1" rowspan="1"><p></p></th><th colspan="1" rowspan="1"><p></p></th></tr><tr><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td></tr><tr><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td><td colspan="1" rowspan="1"><p></p></td></tr></tbody></table>',
      tableStyle: "default",
      visibility: "both",
    },
  },
  {
    type: "audio",
    label: "Audio",
    description: "Audio player with playback controls",
    labelKey: "audio",
    descriptionKey: "audioDesc",
    icon: "Volume2",
    category: "content",
    translations: { de: { label: "Audio", description: "Audioplayer mit Wiedergabesteuerung" } },
    defaultData: { type: "audio", src: "", title: "", visibility: "online" },
  },
  {
    type: "dialogue",
    label: "Dialogue",
    description: "Dialogue with speaker icons and gaps",
    labelKey: "dialogue",
    descriptionKey: "dialogueDesc",
    icon: "MessageCircle",
    category: "interactive",
    translations: { de: { label: "Dialog", description: "Dialog mit Sprechersymbolen und Lücken" } },
    defaultData: {
      type: "dialogue",
      instruction: "",
      items: [
        { id: "dl1", speaker: "A", icon: "triangle", text: "Hello, how are you?" },
        { id: "dl2", speaker: "B", icon: "circle", text: "I am fine, thank you!" },
      ],
      showWordBank: false,
      visibility: "both",
    },
  },
  // ── Layout blocks ──
  {
    type: "spacer",
    label: "Spacer",
    description: "Add vertical spacing",
    labelKey: "spacer",
    descriptionKey: "spacerDesc",
    icon: "Space",
    category: "layout",
    translations: { de: { label: "Abstand", description: "Vertikalen Abstand hinzufügen" } },
    defaultData: { type: "spacer", height: 40, visibility: "both" },
  },
  {
    type: "divider",
    label: "Divider",
    description: "Horizontal line separator",
    labelKey: "divider",
    descriptionKey: "dividerDesc",
    icon: "Minus",
    category: "layout",
    translations: { de: { label: "Trennlinie", description: "Horizontale Trennlinie einfügen" } },
    defaultData: { type: "divider", style: "solid", visibility: "both" },
  },
  {
    type: "logo-divider",
    label: "Logo Divider",
    description: "Centered brand logo as section divider",
    labelKey: "logoDivider",
    descriptionKey: "logoDividerDesc",
    icon: "Sparkle",
    category: "layout",
    translations: { de: { label: "Logo-Trenner", description: "Zentriertes Markenlogo als Abschnittsteiler" } },
    defaultData: { type: "logo-divider", visibility: "both" },
  },
  {
    type: "columns",
    label: "Columns",
    description: "Multi-column layout",
    labelKey: "columnsLabel",
    descriptionKey: "columnsDesc",
    icon: "Columns2",
    category: "layout",
    translations: { de: { label: "Spalten", description: "Inhalt in Spalten anordnen" } },
    defaultData: { type: "columns", columns: 2, children: [[], []], visibility: "both" },
  },
  {
    type: "page-break",
    label: "Page Break",
    description: "Force a page break in print/PDF",
    labelKey: "pageBreak",
    descriptionKey: "pageBreakDesc",
    icon: "FileOutput",
    category: "layout",
    translations: { de: { label: "Seitenumbruch", description: "Seitenumbruch im Druck/PDF erzwingen" } },
    defaultData: { type: "page-break", visibility: "print" },
  },
  {
    type: "writing-lines",
    label: "Writing Lines",
    description: "Dashed lines for handwriting",
    labelKey: "writingLines",
    descriptionKey: "writingLinesDesc",
    icon: "PenLine",
    category: "layout",
    translations: { de: { label: "Schreiblinien", description: "Gestrichelte Linien zum Schreiben" } },
    defaultData: { type: "writing-lines", lineCount: 5, lineSpacing: 24, visibility: "both" },
  },
  {
    type: "writing-rows",
    label: "Writing Rows",
    description: "Numbered rows with writing lines",
    labelKey: "writingRows",
    descriptionKey: "writingRowsDesc",
    icon: "Rows3",
    category: "layout",
    translations: { de: { label: "Schreibzeilen", description: "Nummerierte Zeilen mit Schreiblinien" } },
    defaultData: { type: "writing-rows", rowCount: 5, visibility: "both" },
  },
  // ── Interactive blocks ──
  {
    type: "multiple-choice",
    label: "Multiple Choice",
    description: "Question with selectable answers",
    labelKey: "multipleChoice",
    descriptionKey: "multipleChoiceDesc",
    icon: "CircleDot",
    category: "interactive",
    translations: { de: { label: "Multiple Choice", description: "Fragen mit Antwortoptionen" } },
    defaultData: {
      type: "multiple-choice",
      question: "Enter your question here",
      options: [
        { id: "opt1", text: "Option A", isCorrect: true },
        { id: "opt2", text: "Option B", isCorrect: false },
        { id: "opt3", text: "Option C", isCorrect: false },
        { id: "opt4", text: "Option D", isCorrect: false },
      ],
      allowMultiple: false,
      visibility: "both",
    },
  },
  {
    type: "fill-in-blank",
    label: "Fill in the Blank",
    description: "Text with blanks to fill in",
    labelKey: "fillInBlank",
    descriptionKey: "fillInBlankDesc",
    icon: "TextCursorInput",
    category: "interactive",
    translations: { de: { label: "Lückentext", description: "Sätze mit Lücken zum Ausfüllen" } },
    defaultData: { type: "fill-in-blank", content: "The {{blank:answer}} is the correct word.", visibility: "both" },
  },
  {
    type: "fill-in-blank-items",
    label: "Fill in the Blank (Items)",
    description: "Numbered sentences with blanks to fill in",
    labelKey: "fillInBlankItems",
    descriptionKey: "fillInBlankItemsDesc",
    icon: "TextCursorInput",
    category: "interactive",
    translations: { de: { label: "Lückentext (Sätze)", description: "Nummerierte Sätze mit Lücken zum Ausfüllen" } },
    defaultData: {
      type: "fill-in-blank-items",
      items: [
        { id: "fib1", content: "The {{blank:cat}} sat on the mat." },
        { id: "fib2", content: "She {{blank:goes}} to school every day." },
        { id: "fib3", content: "They {{blank:have}} a big house." },
      ],
      showWordBank: false,
      visibility: "both",
    },
  },
  {
    type: "matching",
    label: "Matching",
    description: "Match items from two columns",
    labelKey: "matching",
    descriptionKey: "matchingDesc",
    icon: "ArrowLeftRight",
    category: "interactive",
    translations: { de: { label: "Zuordnung", description: "Zusammengehörige Paare verbinden" } },
    defaultData: {
      type: "matching",
      instruction: "Match the items on the left with the items on the right.",
      pairs: [
        { id: "p1", left: "Item 1", right: "Match 1" },
        { id: "p2", left: "Item 2", right: "Match 2" },
        { id: "p3", left: "Item 3", right: "Match 3" },
      ],
      extendedRows: false,
      visibility: "both",
    },
  },
  {
    type: "two-column-fill",
    label: "Two-Column Fill",
    description: "Two columns where students fill in one side",
    labelKey: "twoColumnFill",
    descriptionKey: "twoColumnFillDesc",
    icon: "Columns2",
    category: "interactive",
    translations: { de: { label: "Zwei-Spalten-Ausfüllen", description: "Zwei Spalten, eine Seite ausfüllen" } },
    defaultData: {
      type: "two-column-fill",
      instruction: "Fill in the missing items.",
      items: [
        { id: "i1", left: "Item 1", right: "Answer 1" },
        { id: "i2", left: "Item 2", right: "Answer 2" },
        { id: "i3", left: "Item 3", right: "Answer 3" },
      ],
      fillSide: "right",
      colRatio: "1-1",
      extendedRows: false,
      showWordBank: false,
      visibility: "both",
    },
  },
  {
    type: "open-response",
    label: "Open Response",
    description: "Free-form writing area",
    labelKey: "openResponse",
    descriptionKey: "openResponseDesc",
    icon: "PenLine",
    category: "interactive",
    translations: { de: { label: "Offene Antwort", description: "Freitext-Antwortfeld" } },
    defaultData: { type: "open-response", question: "Write your answer below:", lines: 4, visibility: "both" },
  },
  {
    type: "word-bank",
    label: "Word Bank",
    description: "Bank of words for reference",
    labelKey: "wordBank",
    descriptionKey: "wordBankDesc",
    icon: "LayoutList",
    category: "interactive",
    translations: { de: { label: "Wortbank", description: "Wortsammlung als Hilfestellung" } },
    defaultData: { type: "word-bank", words: ["word1", "word2", "word3", "word4"], visibility: "both" },
  },
  {
    type: "true-false-matrix",
    label: "True/False Matrix",
    description: "Evaluate statements as true or false",
    labelKey: "trueFalseMatrix",
    descriptionKey: "trueFalseMatrixDesc",
    icon: "CheckSquare",
    category: "interactive",
    translations: { de: { label: "Richtig/Falsch", description: "Aussagen als richtig oder falsch bewerten" } },
    defaultData: {
      type: "true-false-matrix",
      instruction: "Mark each statement as True or False.",
      statements: [
        { id: "s1", text: "Statement 1", correctAnswer: true },
        { id: "s2", text: "Statement 2", correctAnswer: false },
        { id: "s3", text: "Statement 3", correctAnswer: true },
      ],
      visibility: "both",
    },
  },
  {
    type: "article-training",
    label: "Article Training",
    description: "Practice German articles (der/das/die)",
    labelKey: "articleTraining",
    descriptionKey: "articleTrainingDesc",
    icon: "BookA",
    category: "interactive",
    translations: { de: { label: "Artikel-Training", description: "Deutsche Artikel (der/das/die) üben" } },
    defaultData: {
      type: "article-training",
      instruction: "Kreuze den richtigen Artikel an.",
      showWritingLine: true,
      items: [
        { id: "at1", text: "Hund", correctArticle: "der" },
        { id: "at2", text: "Katze", correctArticle: "die" },
        { id: "at3", text: "Haus", correctArticle: "das" },
      ],
      visibility: "both",
    },
  },
  {
    type: "order-items",
    label: "Order Items",
    description: "Put items in the correct order",
    labelKey: "orderItems",
    descriptionKey: "orderItemsDesc",
    icon: "ListOrdered",
    category: "interactive",
    translations: { de: { label: "Reihenfolge", description: "Elemente in die richtige Reihenfolge bringen" } },
    defaultData: {
      type: "order-items",
      instruction: "Put the following items in the correct order.",
      items: [
        { id: "oi1", text: "First item", correctPosition: 1 },
        { id: "oi2", text: "Second item", correctPosition: 2 },
        { id: "oi3", text: "Third item", correctPosition: 3 },
        { id: "oi4", text: "Fourth item", correctPosition: 4 },
      ],
      visibility: "both",
    },
  },
  {
    type: "inline-choices",
    label: "Inline Choices",
    description: "Text with inline multiple choice options",
    labelKey: "inlineChoices",
    descriptionKey: "inlineChoicesDesc",
    icon: "TextSelect",
    category: "interactive",
    translations: { de: { label: "Inline-Auswahl", description: "Auswahlmöglichkeiten im Text" } },
    defaultData: {
      type: "inline-choices",
      items: [{ id: "ic-default-1", content: "In {{1988|1889|1898}} he was born in London." }],
      visibility: "both",
    },
  },
  {
    type: "word-search",
    label: "Word Search",
    description: "Word search puzzle grid",
    labelKey: "wordSearch",
    descriptionKey: "wordSearchDesc",
    icon: "Search",
    category: "interactive",
    translations: { de: { label: "Wörterrätsel", description: "Versteckte Wörter im Buchstabengitter finden" } },
    defaultData: {
      type: "word-search",
      words: ["HELLO", "WORLD", "SEARCH", "FIND"],
      gridCols: 24,
      gridRows: 12,
      grid: [],
      showWordList: true,
      visibility: "both",
    },
  },
  {
    type: "sorting-categories",
    label: "Sorting Categories",
    description: "Sort items into labeled categories",
    labelKey: "sortingCategories",
    descriptionKey: "sortingCategoriesDesc",
    icon: "Group",
    category: "interactive",
    translations: { de: { label: "Sortieren", description: "Begriffe in Kategorien einordnen" } },
    defaultData: {
      type: "sorting-categories",
      instruction: "",
      categories: [
        { id: "cat1", label: "Category A", correctItems: ["si1", "si2"] },
        { id: "cat2", label: "Category B", correctItems: ["si3", "si4"] },
      ],
      items: [
        { id: "si1", text: "Item 1" },
        { id: "si2", text: "Item 2" },
        { id: "si3", text: "Item 3" },
        { id: "si4", text: "Item 4" },
      ],
      showWritingLines: true,
      visibility: "both",
    },
  },
  {
    type: "unscramble-words",
    label: "Unscramble Words",
    description: "Unscramble jumbled letters to form words",
    labelKey: "unscrambleWords",
    descriptionKey: "unscrambleWordsDesc",
    icon: "Shuffle",
    category: "interactive",
    translations: { de: { label: "Wörter entwirren", description: "Buchstaben in die richtige Reihenfolge bringen" } },
    defaultData: {
      type: "unscramble-words",
      instruction: "",
      words: [
        { id: "uw1", word: "school" },
        { id: "uw2", word: "teacher" },
        { id: "uw3", word: "garden" },
      ],
      keepFirstLetter: false,
      lowercaseAll: false,
      itemOrder: undefined,
      visibility: "both",
    },
  },
  {
    type: "fix-sentences",
    label: "Fix Sentences",
    description: "Reorder sentence parts into correct order",
    labelKey: "fixSentences",
    descriptionKey: "fixSentencesDesc",
    icon: "WrapText",
    category: "interactive",
    translations: { de: { label: "Sätze korrigieren", description: "Fehlerhafte Sätze berichtigen" } },
    defaultData: {
      type: "fix-sentences",
      instruction: "Put the sentence parts in the correct order.",
      sentences: [
        { id: "fs1", sentence: "The cat | sat on | the mat" },
        { id: "fs2", sentence: "I like | to eat | ice cream" },
      ],
      visibility: "both",
    },
  },
  {
    type: "complete-sentences",
    label: "Complete Sentences",
    description: "Complete sentence beginnings",
    labelKey: "completeSentences",
    descriptionKey: "completeSentencesDesc",
    icon: "TextCursorInput",
    category: "interactive",
    translations: { de: { label: "Sätze vervollständigen", description: "Satzanfänge vervollständigen" } },
    defaultData: {
      type: "complete-sentences",
      instruction: "Vervollständige die Sätze.",
      sentences: [
        { id: "cs1", beginning: "Ich gehe gerne …" },
        { id: "cs2", beginning: "Am Wochenende …" },
      ],
      visibility: "both",
    },
  },
  {
    type: "verb-table",
    label: "Verb Table",
    description: "Conjugation table for verbs",
    labelKey: "verbTable",
    descriptionKey: "verbTableDesc",
    icon: "TableProperties",
    category: "interactive",
    translations: { de: { label: "Verbtabelle", description: "Verbkonjugationen üben" } },
    defaultData: {
      type: "verb-table",
      verb: "machen",
      singularRows: [
        { id: "s1", person: "1. Person", pronoun: "ich", conjugation: "mache" },
        { id: "s2", person: "2. Person", detail: "informell", pronoun: "du", conjugation: "machst" },
        { id: "s3", person: "2. Person", detail: "formell", pronoun: "Sie", conjugation: "machen" },
        { id: "s4", person: "3. Person", pronoun: "er / sie / es", conjugation: "macht" },
      ],
      pluralRows: [
        { id: "p1", person: "1. Person", pronoun: "wir", conjugation: "machen" },
        { id: "p2", person: "2. Person", detail: "informell", pronoun: "ihr", conjugation: "macht" },
        { id: "p3", person: "2. Person", detail: "formell", pronoun: "Sie", conjugation: "machen" },
        { id: "p4", person: "3. Person", pronoun: "sie", conjugation: "machen" },
      ],
      visibility: "both",
    },
  },
  // ── AI Tools ──
  {
    type: "ai-prompt",
    label: "AI Prompt",
    description: "Text input with AI processing",
    labelKey: "aiPrompt",
    descriptionKey: "aiPromptDesc",
    icon: "Sparkles",
    category: "ai-tools",
    translations: { de: { label: "KI-Prompt", description: "Texteingabe mit KI-Verarbeitung" } },
    defaultData: {
      type: "ai-prompt",
      instructions: "",
      description: "",
      variableName: "eingabe",
      prompt: "{{eingabe}}",
      userInput: "",
      aiResult: "",
      visibility: "online",
    },
  },
  {
    type: "ai-tool",
    label: "AI Tool",
    description: "Form-based AI agent with custom fields",
    labelKey: "aiTool",
    descriptionKey: "aiToolDesc",
    icon: "Bot",
    category: "ai-tools",
    translations: { de: { label: "KI-Tool", description: "Formularbasierter KI-Agent mit benutzerdefinierten Feldern" } },
    defaultData: {
      type: "ai-tool",
      toolId: "",
      toolSlug: "",
      toolTitle: "",
      toolDescription: "",
      visibility: "online",
    },
  },
];
