-- Add structured guideline columns to textsorten table
ALTER TABLE textsorten
  ADD COLUMN IF NOT EXISTS register text,
  ADD COLUMN IF NOT EXISTS funktion text[],
  ADD COLUMN IF NOT EXISTS perspektive text,
  ADD COLUMN IF NOT EXISTS textaufbau text[],
  ADD COLUMN IF NOT EXISTS typische_sprachhandlungen text[],
  ADD COLUMN IF NOT EXISTS typische_konnektoren text[],
  ADD COLUMN IF NOT EXISTS textlaenge_richtwert text,
  ADD COLUMN IF NOT EXISTS layout_merkmale text[],
  ADD COLUMN IF NOT EXISTS adressat text,
  ADD COLUMN IF NOT EXISTS signalwoerter text[];

-- ─── UPDATE EXISTING ENTRIES ────────────────────────────────────────────────

UPDATE textsorten SET
  label = 'E-Mail',
  gruppe = 'Korrespondenz',
  sort_order = 10,
  register = 'formell bis informell',
  funktion = ARRAY['informieren', 'anfragen', 'auffordern', 'sich bedanken'],
  perspektive = 'ich',
  textaufbau = ARRAY['Betreffzeile', 'Anrede', 'Einleitung', 'Hauptteil', 'Grussformel'],
  typische_sprachhandlungen = ARRAY['informieren', 'bitten', 'bestätigen', 'nachfragen', 'sich bedanken'],
  typische_konnektoren = ARRAY['bezüglich', 'ausserdem', 'deshalb', 'wie besprochen', 'im Anhang'],
  textlaenge_richtwert = 'kurz bis mittel (50–200)',
  layout_merkmale = ARRAY['Betreffzeile', 'Anrede', 'Absätze', 'Signatur'],
  adressat = 'variabel (Freund, Kollege, Unternehmen, Behörde)',
  signalwoerter = ARRAY['Sehr geehrte/r…', 'Liebe/r…', 'Freundliche Grüsse', 'Vielen Dank im Voraus']
WHERE key = 'email';

UPDATE textsorten SET
  label = 'Messenger / Chat',
  gruppe = 'Korrespondenz',
  sort_order = 11,
  register = 'informell',
  funktion = ARRAY['informieren', 'verabreden', 'unterhalten'],
  perspektive = 'ich, du-Ansprache',
  textaufbau = ARRAY['kurze Nachrichten', 'Frage-Antwort-Wechsel'],
  typische_sprachhandlungen = ARRAY['vorschlagen', 'zustimmen', 'ablehnen', 'verabreden', 'reagieren'],
  typische_konnektoren = ARRAY['ok', 'also', 'übrigens', 'btw', 'und'],
  textlaenge_richtwert = 'kurz (20–80)',
  layout_merkmale = ARRAY['Sprechblasen', 'Emojis', 'Zeitstempel', 'kurze Zeilen'],
  adressat = 'Freund, Bekannter, Familie',
  signalwoerter = ARRAY['Hey', 'Na?', 'Bis gleich', 'Alles klar']
WHERE key = 'messenger';

UPDATE textsorten SET
  label = 'Brief',
  gruppe = 'Korrespondenz',
  sort_order = 12,
  register = 'formell bis halbformell',
  funktion = ARRAY['informieren', 'anfragen', 'mitteilen', 'sich bedanken'],
  perspektive = 'ich',
  textaufbau = ARRAY['Absender', 'Empfänger', 'Ort/Datum', 'Betreff', 'Anrede', 'Einleitung', 'Hauptteil', 'Schluss', 'Grussformel', 'Unterschrift'],
  typische_sprachhandlungen = ARRAY['mitteilen', 'bitten', 'informieren', 'sich vorstellen', 'Bezug nehmen'],
  typische_konnektoren = ARRAY['bezüglich', 'hiermit', 'darüber hinaus', 'aus diesem Grund', 'mit Bezug auf'],
  textlaenge_richtwert = 'mittel (150–300)',
  layout_merkmale = ARRAY['Briefkopf', 'Datum', 'Betreffzeile', 'Absätze', 'Unterschrift'],
  adressat = 'Behörde, Unternehmen, Vermieter, Bekannte',
  signalwoerter = ARRAY['Sehr geehrte Damen und Herren', 'Freundliche Grüsse', 'Hiermit möchte ich…']
WHERE key = 'brief';

UPDATE textsorten SET
  label = 'Erzählung',
  gruppe = 'Erzählende Texte',
  sort_order = 20,
  register = 'informell bis halbformell',
  funktion = ARRAY['erzählen', 'unterhalten'],
  perspektive = 'ich oder er/sie',
  textaufbau = ARRAY['Einleitung (Setting)', 'Aufbau/Entwicklung', 'Höhepunkt', 'Schluss/Auflösung'],
  typische_sprachhandlungen = ARRAY['erzählen', 'beschreiben', 'Gefühle ausdrücken', 'Handlung darstellen'],
  typische_konnektoren = ARRAY['plötzlich', 'dann', 'danach', 'zuerst', 'schliesslich', 'als', 'während'],
  textlaenge_richtwert = 'mittel bis lang (200–500)',
  layout_merkmale = ARRAY['Titel', 'Absätze', 'evtl. Dialoge'],
  adressat = 'Leserschaft allgemein',
  signalwoerter = ARRAY['Es war einmal…', 'An einem…', 'Plötzlich…', 'Am Ende…']
WHERE key = 'erzaehlung';

UPDATE textsorten SET
  label = 'Tagebucheintrag',
  gruppe = 'Erzählende Texte',
  sort_order = 21,
  register = 'informell',
  funktion = ARRAY['erzählen', 'reflektieren'],
  perspektive = 'ich',
  textaufbau = ARRAY['Datum', 'Schilderung des Tages/Erlebnisses', 'Gefühle/Gedanken', 'Ausblick'],
  typische_sprachhandlungen = ARRAY['erzählen', 'reflektieren', 'Gefühle ausdrücken'],
  typische_konnektoren = ARRAY['heute', 'dann', 'danach', 'ausserdem', 'leider', 'zum Glück'],
  textlaenge_richtwert = 'kurz bis mittel (80–200)',
  layout_merkmale = ARRAY['Datum', 'Ich-Form', 'Absätze'],
  adressat = 'Ich (privat)',
  signalwoerter = ARRAY['Liebes Tagebuch,', 'Heute war…', 'Ich habe mich…', 'Morgen werde ich…']
WHERE key = 'tagebuch';

UPDATE textsorten SET
  label = 'Porträt',
  gruppe = 'Erzählende Texte',
  sort_order = 22,
  register = 'halbformell',
  funktion = ARRAY['beschreiben', 'informieren', 'vorstellen'],
  perspektive = 'er/sie, neutral',
  textaufbau = ARRAY['Einleitung (Vorstellung der Person)', 'Hintergrund/Werdegang', 'Besonderheiten/Charakter', 'Schluss/Fazit'],
  typische_sprachhandlungen = ARRAY['beschreiben', 'charakterisieren', 'zitieren', 'Hintergründe darstellen'],
  typische_konnektoren = ARRAY['ausserdem', 'besonders', 'bereits', 'trotzdem', 'darüber hinaus'],
  textlaenge_richtwert = 'mittel (150–350)',
  layout_merkmale = ARRAY['Titel', 'Absätze', 'evtl. Zitate', 'evtl. Foto'],
  adressat = 'Leserschaft allgemein',
  signalwoerter = ARRAY['… ist bekannt für…', 'Aufgewachsen in…', 'Was ihn/sie auszeichnet…']
WHERE key = 'portraet';

UPDATE textsorten SET
  label = 'Beschreibung',
  gruppe = 'Erzählende Texte',
  sort_order = 23,
  register = 'halbformell bis neutral',
  funktion = ARRAY['beschreiben', 'informieren'],
  perspektive = 'neutral/unpersönlich',
  textaufbau = ARRAY['Überblick', 'Details (vom Allgemeinen zum Besonderen)', 'Zusammenfassung/Eindruck'],
  typische_sprachhandlungen = ARRAY['beschreiben', 'vergleichen', 'lokalisieren', 'Eigenschaften benennen'],
  typische_konnektoren = ARRAY['links', 'rechts', 'oben', 'im Vordergrund', 'ausserdem', 'im Vergleich zu'],
  textlaenge_richtwert = 'kurz bis mittel (80–250)',
  layout_merkmale = ARRAY['Absätze', 'evtl. Zwischenüberschriften'],
  adressat = 'Leserschaft allgemein',
  signalwoerter = ARRAY['Man sieht…', 'Im Zentrum steht…', 'Auffällig ist…', 'Es handelt sich um…']
WHERE key = 'beschreibung';

UPDATE textsorten SET
  label = 'Dialog / Interview',
  gruppe = 'Mündliche Texte',
  sort_order = 30,
  register = 'informell bis halbformell',
  funktion = ARRAY['informieren', 'erzählen', 'Meinung äussern'],
  perspektive = 'ich, du-Ansprache, Wechsel',
  textaufbau = ARRAY['Begrüssung', 'Einstiegsfrage/Thema', 'Frage-Antwort-Wechsel', 'Zusammenfassung/Abschluss', 'Verabschiedung'],
  typische_sprachhandlungen = ARRAY['fragen', 'antworten', 'nachfragen', 'zustimmen', 'widersprechen', 'erzählen'],
  typische_konnektoren = ARRAY['also', 'naja', 'genau', 'und zwar', 'eigentlich', 'stimmt'],
  textlaenge_richtwert = 'mittel (150–350)',
  layout_merkmale = ARRAY['Sprecherkennzeichnung', 'Wechsel der Redebeiträge'],
  adressat = 'Gesprächspartner',
  signalwoerter = ARRAY['Erzähl mal…', 'Wie siehst du das?', 'Das finde ich auch', 'Stimmt, aber…']
WHERE key = 'dialog';

UPDATE textsorten SET
  label = 'Anleitung',
  gruppe = 'Sachtexte',
  sort_order = 41,
  register = 'neutral bis halbformell',
  funktion = ARRAY['auffordern', 'erklären', 'informieren'],
  perspektive = 'du/Sie-Ansprache oder unpersönlich (man)',
  textaufbau = ARRAY['Ziel/Einleitung', 'Material/Voraussetzungen', 'Schritte (nummeriert)', 'evtl. Tipps/Hinweise'],
  typische_sprachhandlungen = ARRAY['anweisen', 'erklären', 'warnen', 'Tipps geben'],
  typische_konnektoren = ARRAY['zuerst', 'dann', 'anschliessend', 'danach', 'zum Schluss', 'wichtig'],
  textlaenge_richtwert = 'kurz bis mittel (100–250)',
  layout_merkmale = ARRAY['nummerierte Schritte', 'evtl. Bilder/Icons', 'Hervorhebungen'],
  adressat = 'Anwender, Lernende',
  signalwoerter = ARRAY['Schritt 1:', 'Achten Sie darauf…', 'Wichtig:', 'Tipp:']
WHERE key = 'anleitung';

UPDATE textsorten SET
  label = 'Nachricht / Meldung',
  gruppe = 'Sachtexte',
  sort_order = 42,
  register = 'formell, neutral',
  funktion = ARRAY['informieren'],
  perspektive = 'neutral/unpersönlich',
  textaufbau = ARRAY['Schlagzeile', 'Lead (Wer? Was? Wann? Wo?)', 'Details', 'Hintergrund/Kontext', 'evtl. Zitat/Ausblick'],
  typische_sprachhandlungen = ARRAY['berichten', 'zitieren', 'Fakten darstellen'],
  typische_konnektoren = ARRAY['laut', 'wie … berichtet', 'bereits', 'inzwischen', 'demnach'],
  textlaenge_richtwert = 'kurz bis mittel (100–250)',
  layout_merkmale = ARRAY['Schlagzeile', 'Lead-Absatz', 'kurze Absätze'],
  adressat = 'Leserschaft allgemein',
  signalwoerter = ARRAY['Wie die Polizei mitteilte…', 'Am gestrigen…', 'Laut Angaben von…']
WHERE key = 'nachricht';

UPDATE textsorten SET
  label = 'Bericht',
  gruppe = 'Sachtexte',
  sort_order = 43,
  register = 'formell, neutral',
  funktion = ARRAY['informieren', 'dokumentieren'],
  perspektive = 'neutral/unpersönlich',
  textaufbau = ARRAY['Titel', 'Einleitung (Kontext)', 'chronologische/thematische Darstellung', 'Ergebnis/Fazit'],
  typische_sprachhandlungen = ARRAY['berichten', 'zusammenfassen', 'dokumentieren', 'Ergebnisse darstellen'],
  typische_konnektoren = ARRAY['zunächst', 'anschliessend', 'daraufhin', 'abschliessend', 'insgesamt'],
  textlaenge_richtwert = 'mittel bis lang (200–500)',
  layout_merkmale = ARRAY['Titel', 'Zwischenüberschriften', 'Absätze', 'evtl. Daten/Tabellen'],
  adressat = 'Leserschaft allgemein, Fachpublikum',
  signalwoerter = ARRAY['Im Rahmen von…', 'Die Ergebnisse zeigen…', 'Zusammenfassend lässt sich sagen…']
WHERE key = 'bericht';

UPDATE textsorten SET
  label = 'Inserat / Anzeige',
  gruppe = 'Sachtexte',
  sort_order = 44,
  register = 'halbformell bis informell',
  funktion = ARRAY['informieren', 'auffordern', 'überzeugen'],
  perspektive = 'wir, du/Sie-Ansprache',
  textaufbau = ARRAY['Überschrift/Eyecatcher', 'Angebot/Beschreibung', 'Details (Preis, Kontakt, Bedingungen)', 'Handlungsaufforderung'],
  typische_sprachhandlungen = ARRAY['anbieten', 'beschreiben', 'auffordern', 'überzeugen'],
  typische_konnektoren = ARRAY['nur', 'jetzt', 'ab sofort', 'inklusive', 'bei Interesse'],
  textlaenge_richtwert = 'kurz (30–120)',
  layout_merkmale = ARRAY['Überschrift gross', 'Stichpunkte', 'Kontaktdaten', 'Preis hervorgehoben'],
  adressat = 'Käufer, Mieter, Interessierte',
  signalwoerter = ARRAY['Zu verkaufen:', 'Ab sofort verfügbar', 'Jetzt zugreifen!', 'Bei Interesse melden unter…']
WHERE key = 'inserat';

UPDATE textsorten SET
  label = 'Kommentar',
  gruppe = 'Meinungstexte',
  sort_order = 60,
  register = 'halbformell',
  funktion = ARRAY['Meinung äussern', 'überzeugen', 'argumentieren'],
  perspektive = 'ich',
  textaufbau = ARRAY['These/Standpunkt', 'Argumente', 'Beispiele', 'Schlussfolgerung'],
  typische_sprachhandlungen = ARRAY['Meinung äussern', 'begründen', 'bewerten', 'kritisieren', 'fordern'],
  typische_konnektoren = ARRAY['meiner Meinung nach', 'einerseits … andererseits', 'deshalb', 'dennoch', 'man muss bedenken'],
  textlaenge_richtwert = 'mittel (150–300)',
  layout_merkmale = ARRAY['Titel', 'Absätze'],
  adressat = 'Leserschaft allgemein',
  signalwoerter = ARRAY['Ich finde, dass…', 'Man sollte…', 'Es ist höchste Zeit…', 'Abschliessend möchte ich betonen…']
WHERE key = 'kommentar';

-- ─── INSERT NEW ENTRIES ──────────────────────────────────────────────────────

INSERT INTO textsorten (key, label, gruppe, anweisung, is_personal, is_dialog, sort_order,
  register, funktion, perspektive, textaufbau, typische_sprachhandlungen, typische_konnektoren,
  textlaenge_richtwert, layout_merkmale, adressat, signalwoerter)
VALUES
  -- Korrespondenz
  ('einladung', 'Einladung', 'Korrespondenz',
   'Einladung: mit Anlass, Datum/Zeit/Ort, Bitte um Rückmeldung und Grussformel.',
   true, false, 13,
   'halbformell bis informell',
   ARRAY['einladen', 'informieren', 'auffordern'],
   'ich/wir',
   ARRAY['Anrede', 'Anlass', 'Details (Ort, Zeit, Programm)', 'Bitte um Rückmeldung', 'Grussformel'],
   ARRAY['einladen', 'informieren', 'bitten', 'sich freuen'],
   ARRAY['anlässlich', 'deshalb', 'bitte', 'wir würden uns freuen'],
   'kurz bis mittel (80–200)',
   ARRAY['Anlass hervorgehoben', 'Datum/Ort/Zeit klar strukturiert', 'evtl. RSVP-Hinweis'],
   'Freunde, Familie, Kollegen, Nachbarn',
   ARRAY['Wir laden euch herzlich ein', 'Du bist herzlich eingeladen', 'Bitte gib uns bis … Bescheid']),

  ('bewerbung', 'Bewerbungsschreiben', 'Korrespondenz',
   'Bewerbungsschreiben: formell, mit Bezug auf Stelle, eigene Qualifikationen und Motivation; mit Grussformel.',
   true, false, 14,
   'formell',
   ARRAY['überzeugen', 'sich vorstellen', 'begründen'],
   'ich',
   ARRAY['Absender', 'Empfänger', 'Datum', 'Betreff', 'Anrede', 'Einleitung (Bezug auf Stelle)', 'Qualifikationen', 'Motivation', 'Schluss', 'Grussformel'],
   ARRAY['sich vorstellen', 'Kompetenzen beschreiben', 'Motivation begründen', 'Bezug auf Stellenanzeige nehmen'],
   ARRAY['darüber hinaus', 'aufgrund', 'deshalb', 'zudem', 'ich bin überzeugt'],
   'mittel (200–350)',
   ARRAY['Briefformat', 'Betreffzeile mit Stellenbezeichnung', 'Absätze', 'Unterschrift'],
   'Arbeitgeber, Personalabteilung',
   ARRAY['Hiermit bewerbe ich mich um…', 'Mit grossem Interesse habe ich…', 'Ich bringe … mit', 'Freundliche Grüsse']),

  ('beschwerde', 'Beschwerde / Reklamation', 'Korrespondenz',
   'Beschwerde/Reklamation: mit klarer Problembeschreibung, Forderung und ggf. Fristsetzung; formell.',
   true, false, 15,
   'formell',
   ARRAY['auffordern', 'beschreiben', 'begründen'],
   'ich',
   ARRAY['Betreffzeile', 'Anrede', 'Problembeschreibung', 'Begründung/Auswirkung', 'Forderung', 'Fristsetzung', 'Grussformel'],
   ARRAY['sich beschweren', 'einen Sachverhalt schildern', 'eine Forderung stellen', 'auf Fristen hinweisen', 'Enttäuschung ausdrücken'],
   ARRAY['leider', 'trotzdem', 'deshalb', 'aus diesem Grund', 'ich bitte Sie daher', 'andernfalls'],
   'mittel (150–300)',
   ARRAY['Absenderadresse', 'Datum', 'Betreffzeile', 'Briefformat'],
   'Unternehmen, Vermieter, Behörde',
   ARRAY['Sehr geehrte Damen und Herren', 'Ich möchte mich beschweren über…', 'Ich fordere Sie auf…', 'Freundliche Grüsse']),

  -- Erzählende Texte
  ('socialmedia', 'Social Media Post', 'Erzählende Texte',
   'Social-Media-Post: kurz, informell, mit persönlicher Note; ggf. Hashtags oder Emojis.',
   true, false, 24,
   'informell',
   ARRAY['erzählen', 'unterhalten', 'Meinung äussern', 'informieren'],
   'ich',
   ARRAY['Aufhänger/Hook', 'kurze Schilderung', 'persönliche Bewertung', 'Hashtags'],
   ARRAY['berichten', 'kommentieren', 'empfehlen', 'Gefühle ausdrücken', 'zum Interagieren auffordern'],
   ARRAY['übrigens', 'aber', 'mega', 'so'],
   'kurz (30–150)',
   ARRAY['Emojis', 'Hashtags', 'Zeilenumbrüche als Stilmittel', 'evtl. Bild-/Videobezug'],
   'Follower, Online-Community',
   ARRAY['Was für ein Tag!', 'Kennt ihr das?', '#throwback', 'Was meint ihr?']),

  ('erlebnisbericht', 'Erlebnisbericht', 'Erzählende Texte',
   'Erlebnisbericht: persönlich, chronologisch, mit persönlicher Bewertung.',
   true, false, 25,
   'halbformell bis informell',
   ARRAY['erzählen', 'beschreiben', 'informieren'],
   'ich',
   ARRAY['Einleitung (Kontext)', 'chronologische Schilderung', 'persönliche Bewertung', 'Schluss'],
   ARRAY['erzählen', 'beschreiben', 'Gefühle ausdrücken', 'bewerten'],
   ARRAY['zuerst', 'dann', 'danach', 'schliesslich', 'besonders', 'am meisten'],
   'mittel (150–300)',
   ARRAY['Titel', 'Absätze'],
   'Leserschaft allgemein, Kursgruppe',
   ARRAY['Letztes Wochenende…', 'Das war ein besonderes Erlebnis', 'Am besten hat mir gefallen…']),

  ('reisebericht', 'Reisebericht', 'Erzählende Texte',
   'Reisebericht: persönlich, chronologisch, mit Highlights und Fazit/Empfehlung.',
   true, false, 26,
   'halbformell bis informell',
   ARRAY['erzählen', 'beschreiben', 'empfehlen', 'informieren'],
   'ich/wir',
   ARRAY['Einleitung (Reiseziel, Anlass)', 'chronologische Schilderung', 'Highlights', 'Fazit/Empfehlung'],
   ARRAY['erzählen', 'beschreiben', 'empfehlen', 'vergleichen', 'bewerten'],
   ARRAY['am ersten Tag', 'danach', 'besonders', 'im Vergleich zu', 'abschliessend'],
   'mittel bis lang (200–500)',
   ARRAY['Titel', 'Absätze', 'evtl. Zwischenüberschriften', 'evtl. Fotobezüge'],
   'Leserschaft allgemein, Reiseinteressierte',
   ARRAY['Unsere Reise ging nach…', 'Ein Highlight war…', 'Ich kann … nur empfehlen']),

  -- Mündliche Texte
  ('telefongespraech', 'Telefongespräch', 'Mündliche Texte',
   'Telefongespräch: mit Meldung, Anliegen, Informationsaustausch und Verabschiedung; kurze Turns.',
   true, true, 31,
   'halbformell bis formell',
   ARRAY['informieren', 'anfragen', 'vereinbaren'],
   'ich, du/Sie-Ansprache, Wechsel',
   ARRAY['Begrüssung/Meldung', 'Anliegen nennen', 'Informationsaustausch', 'Vereinbarung/Ergebnis', 'Verabschiedung'],
   ARRAY['sich melden', 'Anliegen formulieren', 'nachfragen', 'bestätigen', 'vereinbaren'],
   ARRAY['es geht um', 'könnten Sie', 'ich wollte fragen', 'also dann', 'vielen Dank'],
   'kurz bis mittel (80–200)',
   ARRAY['Sprecherkennzeichnung', 'kurze Turns'],
   'Arztpraxis, Behörde, Kundenservice, Bekannte',
   ARRAY['Guten Tag, mein Name ist…', 'Ich rufe an wegen…', 'Könnten Sie mir sagen…', 'Auf Wiederhören']),

  ('diskussion', 'Diskussion / Debatte', 'Mündliche Texte',
   'Diskussion/Debatte: mit Sprecherwechsel, Meinungsäusserung, Begründung und Gegenargumenten.',
   true, true, 32,
   'halbformell',
   ARRAY['Meinung äussern', 'überzeugen', 'argumentieren'],
   'ich, Wechsel',
   ARRAY['Thema/Fragestellung', 'These', 'Argument-Gegenargument', 'Stellungnahme', 'evtl. Kompromiss/Fazit'],
   ARRAY['Meinung äussern', 'begründen', 'widersprechen', 'zustimmen', 'einlenken', 'zusammenfassen'],
   ARRAY['meiner Meinung nach', 'einerseits … andererseits', 'ich sehe das anders', 'trotzdem', 'obwohl'],
   'mittel (150–350)',
   ARRAY['Sprecherkennzeichnung', 'Wechsel der Redebeiträge'],
   'Diskussionsteilnehmer',
   ARRAY['Ich bin der Meinung, dass…', 'Da bin ich anderer Meinung', 'Das stimmt, aber…', 'Einverstanden, jedoch…']),

  ('vortrag', 'Vortrag / Präsentation', 'Mündliche Texte',
   'Vortrag/Präsentation: mit Gliederung, Hauptteil und Zusammenfassung; halbformell bis formell.',
   false, false, 33,
   'halbformell bis formell',
   ARRAY['informieren', 'erklären', 'überzeugen'],
   'ich/wir',
   ARRAY['Begrüssung', 'Thema/Gliederung', 'Hauptteil mit Abschnitten', 'Zusammenfassung', 'Dank/Fragen'],
   ARRAY['informieren', 'erklären', 'Beispiele geben', 'zusammenfassen', 'zum Fragen auffordern'],
   ARRAY['zunächst', 'dann', 'ein weiterer Punkt', 'zusammenfassend', 'abschliessend'],
   'mittel bis lang (200–500)',
   ARRAY['Gliederungspunkte', 'Sprechtext', 'evtl. Folienbezüge'],
   'Publikum, Kursgruppe, Fachpublikum',
   ARRAY['Ich möchte heute über … sprechen', 'Kommen wir zum nächsten Punkt', 'Haben Sie noch Fragen?']),

  ('durchsage', 'Durchsage / Ansage', 'Mündliche Texte',
   'Durchsage: kurz, klar, unpersönlich; mit konkreter Information und Handlungsaufforderung.',
   false, false, 34,
   'formell',
   ARRAY['informieren', 'auffordern', 'warnen'],
   'wir, unpersönlich',
   ARRAY['Ansprache', 'Information/Warnung', 'Handlungsaufforderung', 'evtl. Wiederholung'],
   ARRAY['informieren', 'auffordern', 'bitten', 'warnen'],
   ARRAY['bitte beachten Sie', 'wir bitten Sie', 'aufgrund', 'wir informieren Sie'],
   'kurz (30–100)',
   ARRAY['kurze Sätze', 'klare Struktur', 'evtl. Wiederholung'],
   'Reisende, Kunden, Öffentlichkeit',
   ARRAY['Achtung, eine Durchsage', 'Sehr geehrte Fahrgäste', 'Wir bitten Sie…', 'Vielen Dank für Ihr Verständnis']),

  -- Sachtexte
  ('informationstext', 'Informationstext', 'Sachtexte',
   'Informationstext: neutrale Tonalität, klare Struktur mit Absätzen, Fakten und Beispiele einfach formuliert.',
   false, false, 40,
   'neutral bis formell',
   ARRAY['informieren', 'erklären'],
   'neutral/unpersönlich',
   ARRAY['Titel', 'Einleitung', 'Hauptteil mit Abschnitten', 'evtl. Fazit'],
   ARRAY['informieren', 'erklären', 'definieren', 'Beispiele geben', 'vergleichen'],
   ARRAY['ausserdem', 'jedoch', 'beispielsweise', 'das bedeutet', 'im Gegensatz zu'],
   'mittel bis lang (200–500)',
   ARRAY['Titel', 'Zwischenüberschriften', 'Absätze', 'evtl. Grafiken/Tabellen'],
   'Leserschaft allgemein',
   ARRAY['Unter … versteht man…', 'Studien zeigen…', 'Ein Beispiel dafür ist…']),

  ('checkliste', 'Checkliste', 'Sachtexte',
   'Checkliste: kurze Punkte zum Abhaken, klar strukturiert.',
   false, false, 45,
   'neutral bis halbformell',
   ARRAY['informieren', 'auffordern', 'strukturieren'],
   'unpersönlich oder du/Sie-Ansprache',
   ARRAY['Titel/Thema', 'Punkte zum Abhaken', 'evtl. Hinweise/Tipps'],
   ARRAY['auflisten', 'erinnern', 'auffordern', 'priorisieren'],
   ARRAY['zuerst', 'ausserdem', 'nicht vergessen', 'wichtig', 'optional'],
   'kurz (50–150)',
   ARRAY['Checkboxen/Aufzählungszeichen', 'kurze Punkte', 'evtl. Kategorien'],
   'Anwender, Lernende, Reisende',
   ARRAY['Erledigt?', 'Nicht vergessen:', 'Wichtig:']),

  ('merkblatt', 'Merkblatt', 'Sachtexte',
   'Merkblatt: sachlich, klar gegliedert, mit Hervorhebungen und Kontaktangaben.',
   false, false, 46,
   'neutral bis formell',
   ARRAY['informieren', 'erklären', 'auffordern'],
   'unpersönlich oder Sie-Ansprache',
   ARRAY['Titel', 'Zweck/Einleitung', 'Kernpunkte (gegliedert)', 'Kontakt/Anlaufstelle'],
   ARRAY['informieren', 'erklären', 'auf Regeln hinweisen', 'Anlaufstellen nennen'],
   ARRAY['bitte beachten Sie', 'grundsätzlich', 'in diesem Fall', 'weitere Informationen'],
   'kurz bis mittel (100–250)',
   ARRAY['Titel', 'Absätze', 'Aufzählungen', 'Hervorhebungen', 'Kontaktdaten'],
   'Bürger, Patienten, Mieter, Lernende',
   ARRAY['Bitte beachten Sie…', 'Wichtige Hinweise:', 'Bei Fragen wenden Sie sich an…']),

  ('faq', 'FAQ', 'Sachtexte',
   'FAQ: Frage-Antwort-Paare, klar und knapp.',
   false, false, 47,
   'halbformell bis neutral',
   ARRAY['informieren', 'erklären'],
   'unpersönlich oder du/Sie-Ansprache',
   ARRAY['Frage', 'Antwort', 'Frage', 'Antwort'],
   ARRAY['fragen', 'erklären', 'klarstellen', 'auf Ausnahmen hinweisen'],
   ARRAY['grundsätzlich', 'in der Regel', 'falls', 'bitte beachten Sie', 'das hängt davon ab'],
   'kurz pro Frage-Antwort-Paar (30–80)',
   ARRAY['Frage fett/hervorgehoben', 'Antwort darunter', 'thematische Gruppierung'],
   'Kunden, Nutzer, Lernende',
   ARRAY['Wie kann ich…?', 'Was passiert, wenn…?', 'Muss ich…?']),

  ('ratgebertext', 'Ratgebertext', 'Sachtexte',
   'Ratgebertext: mit Tipps, Begründungen und Zusammenfassung; du/Sie-Ansprache oder unpersönlich.',
   false, false, 48,
   'halbformell bis informell',
   ARRAY['informieren', 'empfehlen', 'überzeugen'],
   'du/Sie-Ansprache oder unpersönlich',
   ARRAY['Einleitung (Problem/Frage)', 'Tipps/Empfehlungen', 'Begründungen', 'Zusammenfassung'],
   ARRAY['empfehlen', 'raten', 'warnen', 'begründen', 'Tipps geben'],
   ARRAY['am besten', 'ausserdem', 'vermeiden Sie', 'es empfiehlt sich', 'ein weiterer Tipp'],
   'mittel (150–350)',
   ARRAY['Titel', 'Zwischenüberschriften', 'nummerierte Tipps', 'evtl. Infoboxen'],
   'Ratsuchende, Leserschaft allgemein',
   ARRAY['5 Tipps für…', 'So gelingt…', 'Achten Sie darauf…', 'Unser Tipp:']),

  ('programmheft', 'Programmheft / Veranstaltungshinweis', 'Sachtexte',
   'Programmheft/Veranstaltungshinweis: mit Datum, Ort, Programmpunkten und Kontaktdaten.',
   false, false, 49,
   'halbformell bis neutral',
   ARRAY['informieren', 'einladen', 'auffordern'],
   'wir, unpersönlich',
   ARRAY['Titel/Veranstaltungsname', 'Datum/Ort/Zeit', 'Programmpunkte', 'Anmeldung/Kontakt'],
   ARRAY['informieren', 'einladen', 'beschreiben', 'auf Details hinweisen'],
   ARRAY['um … Uhr', 'anschliessend', 'im Anschluss', 'Eintritt frei', 'Anmeldung unter'],
   'kurz bis mittel (80–200)',
   ARRAY['Datum/Ort hervorgehoben', 'Programmablauf', 'Kontaktdaten', 'evtl. Logo'],
   'Interessierte, Öffentlichkeit',
   ARRAY['Herzlich willkommen zu…', 'Programm:', 'Eintritt:', 'Anmeldung bis…']),

  ('regelwerk', 'Regelwerk', 'Sachtexte',
   'Regelwerk: nummerierte Punkte, formell, mit Konsequenzen bei Verstoss.',
   false, false, 50,
   'formell',
   ARRAY['auffordern', 'informieren', 'regeln'],
   'unpersönlich oder Sie-Ansprache',
   ARRAY['Titel', 'Geltungsbereich', 'Regeln/Punkte (nummeriert)', 'Konsequenzen bei Verstoss', 'evtl. Kontakt'],
   ARRAY['vorschreiben', 'verbieten', 'erlauben', 'auf Konsequenzen hinweisen'],
   ARRAY['es ist nicht gestattet', 'bitte beachten Sie', 'bei Verstoss', 'ausnahmsweise', 'grundsätzlich'],
   'kurz bis mittel (100–250)',
   ARRAY['nummerierte Punkte', 'klare Gliederung', 'Hervorhebungen'],
   'Bewohner, Teilnehmer, Mitglieder',
   ARRAY['Es gilt:', 'Es ist untersagt…', 'Bitte beachten Sie:', 'Bei Zuwiderhandlung…']),

  -- Meinungstexte
  ('leserbrief', 'Leserbrief', 'Meinungstexte',
   'Leserbrief: mit Bezug auf Artikel, eigener Meinung und Argumentation; halbformell bis formell.',
   true, false, 61,
   'halbformell bis formell',
   ARRAY['Meinung äussern', 'reagieren', 'argumentieren'],
   'ich',
   ARRAY['Bezug auf Artikel/Thema', 'eigene Meinung', 'Argumente/Beispiele', 'Schluss/Appell'],
   ARRAY['Bezug nehmen', 'Meinung äussern', 'widersprechen', 'zustimmen', 'ergänzen'],
   ARRAY['in Ihrem Artikel', 'ich stimme zu, dass', 'allerdings', 'meines Erachtens', 'daher'],
   'mittel (100–250)',
   ARRAY['Anrede', 'Bezug auf Quelle', 'Absätze', 'Grussformel'],
   'Redaktion, Leserschaft',
   ARRAY['Mit Bezug auf Ihren Artikel…', 'Als Leser/in möchte ich…', 'Ich teile die Meinung, dass…', 'Freundliche Grüsse']),

  ('rezension', 'Rezension / Kritik', 'Meinungstexte',
   'Rezension/Kritik: mit Kurzbeschreibung, Bewertung und Empfehlung.',
   true, false, 62,
   'halbformell',
   ARRAY['bewerten', 'informieren', 'empfehlen'],
   'ich',
   ARRAY['Einleitung (Gegenstand)', 'Zusammenfassung/Beschreibung', 'Bewertung (positiv/negativ)', 'Fazit/Empfehlung'],
   ARRAY['beschreiben', 'bewerten', 'vergleichen', 'empfehlen', 'kritisieren'],
   ARRAY['besonders gut', 'leider', 'im Vergleich zu', 'trotzdem', 'alles in allem'],
   'mittel (150–300)',
   ARRAY['Titel', 'evtl. Sternebewertung', 'Absätze'],
   'Leserschaft allgemein, Kaufinteressierte',
   ARRAY['Das Buch/der Film handelt von…', 'Besonders gelungen ist…', 'Leider enttäuscht…', 'Ich kann … empfehlen']),

  ('blogbeitrag', 'Blogbeitrag', 'Meinungstexte',
   'Blogbeitrag: persönlich, mit Hook, Meinung, Beispielen und Fazit/Call-to-Action.',
   true, false, 63,
   'halbformell bis informell',
   ARRAY['Meinung äussern', 'informieren', 'unterhalten'],
   'ich',
   ARRAY['Aufhänger/Hook', 'persönliche Perspektive', 'Argumente/Beispiele', 'Fazit/Call-to-Action'],
   ARRAY['erzählen', 'Meinung äussern', 'empfehlen', 'zum Nachdenken anregen'],
   ARRAY['ehrlich gesagt', 'was ich damit meine', 'ausserdem', 'kurz gesagt', 'was denkt ihr?'],
   'mittel (150–400)',
   ARRAY['Titel', 'Zwischenüberschriften', 'Absätze', 'evtl. Bilder', 'Kommentarfunktion'],
   'Blog-Leserschaft, Online-Community',
   ARRAY['Heute möchte ich über … schreiben', 'Kennt ihr das?', 'Was meint ihr?', 'Schreibt mir in die Kommentare']),

  ('essay', 'Erörterung / Essay', 'Meinungstexte',
   'Erörterung/Essay: formal, mit These, Pro- und Contra-Argumenten und Fazit.',
   false, false, 64,
   'formell bis halbformell',
   ARRAY['argumentieren', 'überzeugen', 'erklären'],
   'ich oder unpersönlich',
   ARRAY['Einleitung (Fragestellung)', 'These', 'Pro-Argumente', 'Contra-Argumente', 'Synthese/Fazit'],
   ARRAY['argumentieren', 'begründen', 'abwägen', 'Beispiele anführen', 'Schlüsse ziehen'],
   ARRAY['einerseits … andererseits', 'darüber hinaus', 'obwohl', 'zusammenfassend', 'es lässt sich feststellen'],
   'lang (300–600)',
   ARRAY['Titel', 'Absätze', 'klare Argumentation'],
   'Prüfungskontext, Fachpublikum, Leserschaft',
   ARRAY['Die Frage, ob…', 'Dafür spricht…', 'Dagegen lässt sich einwenden…', 'Abschliessend lässt sich sagen…'])

ON CONFLICT (key) DO NOTHING;
